server:
   port: 80

spring:
    mvc:
        view:
            suffix: .html
    datasource:
        url: jdbc:oracle:thin:@47.93.190.20:1521:orcl
        username: yi
        password: yi
        driver-class-name: oracle.jdbc.driver.OracleDriver
    servlet:
        multipart:
            max-file-size: 10Mb
            max-request-size: 60Mb

elasticsearch:
    hostname: 192.168.116.130
    port: 9200

fdfs:
    so-timeout: 1501
    connect-timeout: 601
    thumb-image:             #缩略图生成参数
        width: 150
        height: 150
    tracker-list:            #TrackerList参数,支持多个
        - 47.93.190.20:22122
    pool:
    #从池中借出的对象的最大数目
        max-total: 153
      #获取连接时的最大等待毫秒数100
        max-wait-millis: 102

dataServer:
    bathPath:
        http://47.93.190.20:9999/